version: '3'
services:
    db:
        image: postgres:13.3-alpine
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
            # https://stackoverflow.com/questions/41637505/how-to-persist-data-in-a-dockerized-postgres-database-using-volumes
        env_file: .env
    web:
        build:
            context: .
            dockerfile: Dockerfile
        # volumes:
            # - .:/src
            # only run ^ in dev to see code changes
        ports:
            - "3000:3000"
        depends_on:
            - db
        env_file: .env
        environment:
            RAILS_LOG_TO_STDOUT: 'true'
    server:
        image: nginx:mainline-alpine
        container_name: server
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx-conf:/etc/nginx/conf.d
        depends_on:
            - web
volumes:
    db-data: