name: Quick Actions Usage
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  matrix-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run some commands
        run: |
          echo "Running on ${{ matrix.os }} with Node ${{ matrix.node-version }}"
          sleep 60  # Run for 1 minute
          echo "Done!"
